[platformio]
default_envs = sticks3

[env:sticks3]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
upload_speed = 460800
# StickS3 enters download mode with a long press of its Reset button.
board_upload.before_reset = no_reset
build_flags =
    -DESP32S3
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    M5Unified=https://github.com/m5stack/M5Unified#8b63555e7bd9ac71978c55ad868fd1d1d3b2ef3e
    M5PM1=https://github.com/m5stack/M5PM1#be9a5456c007c333e7ac963f33bfde1ffa5d82ee
    M5GFX@0.2.30
    h2zero/NimBLE-Arduino@2.5.1
