[platformio]
src_dir = .

[env]
platform = ststm32
board = nucleo_f411re
framework = arduino


[env:l10_led_blink]
build_src_filter = -<*> +<l10/1.led_blink/>


[env:l10_gpio]
build_src_filter = -<*> +<l10/2.gpio/>
